### PR TITLE
Introduce a link to the deployment

### PR DESCRIPTION
**Pull request by Bernd-L**
Introduces a link to the deployment

### CODE REVIEW

**Comment by AlbericTrancart** [comment]
Thanks! Why did you feel the need to add this? https://www.spacexstats.xyz is also the latest build on master.

**Comment by Bernd-L** [comment]
> Thanks! Why did you feel the need to add this? https://www.spacexstats.xyz is also the latest build on master.

I've just updated the link in my PR.

The point of this PR is to show visitors directly, that the project can be viewed online, and that a local compilation is not necessary. 

When I first discovered this project, I cloned and built the app and served it locally, because I didn't know it was hosted already.

Furthermore, consider also including the link `https://www.spacexstats.xyz` in the "About" section of the Repo metadata (there should be a pencil/gear icon when you hover your cursor there):

image

**Comment by AlbericTrancart** [comment]
@Bernd-L thanks, merged it! I'm interested in how you discovered the repo then. Is it via GitHub? :)

**Comment by Bernd-L** [comment]
> @Bernd-L thanks, merged it! I'm interested in how you discovered the repo then. Is it via GitHub? :)

@AlbericTrancart

1. I watched a video from fireship.io on YouTube
2. He talked about how to use GraphQL and used the SpaceX API as an example
3. I searched for the SpaceX API online
4. There are only unofficial APIs
5. I keep looking through GitHub
6. I found this repo, cloned, built, served
7. Then I found the hosted version :disappointed: 
8. I opened this PR, so others don't have to go through step 6 and can just open it directly.

**Pull request merged**
